### ISSUE TITLE
Missing "We go out" slide

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/outreach-materials#5]
`SSI Introduction.pptx` is missing the "We go out to the communities, not make them come to us" slide.

![screenshot from 2017-09-11 14-41-57](https://user-images.githubusercontent.com/1506457/30277340-62cb0836-96ff-11e7-8224-918e5d8582be.png)

**Comment by npch** [comment]
I no longer have this slide in the set because it is too difficult to keep up to date at present. It was created specifically for the SSI2 bid.

I normally talk about the concept of "going out to the communities" when I mention that the Institute is "virtual" and distributed.

I don't propose adding this to the set unless users of the slides think it is important to introduce the Institute.
